### ISSUE TITLE
Does not work when using sinon.useFakeTimers()

### ISSUE THREAD

**Issue by KevinSnyderCodes** [brummelte/sleep-promise#10]
[sinon](https://github.com/sinonjs/sinon) is a popular stubbing framework for JavaScript unit tests. [`sinon.useFakeTimers()`](http://sinonjs.org/releases/v1.17.7/fake-timers/) replaces the global `setTimeout()` method with its own, allowing unit tests to instantly move time forward instead of waiting for time to pass.

Because this project calls the global `setTimeout()` method, it will not work if `sinon.useFakeTimers()` is called.

A simple solution would be to store the global `setTimeout()` method before sinon replaces it:

`sleep-promise/lib/index.js`

```js
const setTimeout = global.setTimeout;

// sleep() implementation...
```

`someProject/test.js`

```js
const sleep = require('sleep-promise');
const clock = sinon.useFakeTimers();

// Unit test code...
```

If you're ok with this from a design perspective, I'd be happy to open a PR.

**Comment by brummelte** [comment]
Hi @KevinSnyderCodes,

that sounds like a good solution. Would be happy to accept a PR.

**Comment by KevinSnyderCodes** [comment]
Sure, will get around to all of that soon :)

**Comment by brummelte** [comment]
Thank you.

But now thinking about it a bit more. Using the sleep promise in application code could not be forwarded using fake timers anymore then.

Your solution is about enabling the usage in test files isn't it?

**Comment by KevinSnyderCodes** [comment]
Good point. Yeah I'm trying to use sleep-promise in test files without it being affected by fake timers.

Maybe we could add an options parameter to the sleep method that lets one decide whether to use the global setTimeout, or a stored reference. It would default to using the global one.

**Comment by KevinSnyderCodes** [comment]
On second thought, I could solve this by changing the design of the class being tested. It creates a websocket server and expects a message from connected clients every 5 seconds to ensure that they are still there. The class could emit a "messageReceived" event and the unit test could await this event, eliminating the need for sleep-promise. However, this event would really only be useful for unit testing.

It may not make sense for sleep-promise to be responsible for fake timers being used. Your call.

**Comment by brummelte** [comment]
First I thought the best way would be for you to write a helper function that uses clock.restore() then calls sleep and then calls sinon.useFakeTimers again. But I guess that is nearly as long as just reimplementing a basic sleep promise.

I will have to think about it a little more. I can see the use case. So adding such a function probably also makes sense for other people. Right now I'm leaning towards a second exported function. Something like 'sleepWithRealTimers' :-)

Need to think about it a bit more and if I go that route, need to think about a better name.

**Comment by KevinSnyderCodes** [comment]
I like to use `options` object parameters because:

- They're an optional last parameter and don't affect the existing function signature
- They can be extended at any point to support more options
- Making a second function with 90% of the same functionality doesn't make sense IMO, when you can indicate small changes in the `options` object

**Comment by brummelte** [comment]
I agree. Maybe I can add it this evening, but probably it will take till the weekend until I have time. You can create a PR if you want to.

If you want to work on it, please use object destructuring in the parameters for the options with default values. And I think `useStoredReference` is not descriptive enough. I think something like `useCachedSetTimeout` would be better. But maybe you can find a better name. And the default should be false not true.

```js
export default sleep(timeout, { useCachedSetTimeout } = {}) {
    // …
}
```

**Comment by KevinSnyderCodes** [comment]
Agree with everything you said. PR will be up this afternoon.
