### ISSUE TITLE
Feature request: cancel promise

### ISSUE THREAD

**Issue by ssut** [brummelte/sleep-promise#13]
I'm using this library for handling timeout stuffs or something else like:

```javascript
await Promise.all([
  triggerPromise(),
  Promise.race([
    eventPromise.then(...), // event might be invoked or not
    sleep(1000).then(() => Promise.reject('timeout exceeded of 1000ms while ...')), // timeout
  ]),
]);
```

(feature request)
In the case above all things are good, however I have faced a situation where the sleep promise should be cancelled to continue, as like:

```javascript
const timeout = sleep(1000).then(() => Promise.reject(...));
await Promise.all([
  triggerPromise(),
  Promise.race([
    eventPromise.then(() => {
      timeout.cancel(); // here
      return operationPromiseThatTakesMoreThanTimeout();
    }),
    timeout,
  ]);
]);
```

(current solution)
Anyway, this goal can be reached by writing code like as follows:

```javascript
const timeout = sleep(1000).then(() => Promise.reject(...));
await Promise.all([
  triggerPromise(),
  new Promise((resolve, reject) => {
    let handled = false;

    eventPromise.then(() => {
      handled = true;
      operationPromiseThatTakesMoreThanTimeout().then(resolve);
    });

    sleep(1000).then(() => { // or `setTimeout`
      if (handled) {
        return;
      }
      reject(...);
    });
  }),
]);
```
(or similar)

but you may know this is bad idea/style, just because if sleep-promise supports promise cancellation for the case like this.

**Comment by kachkaev** [comment]
Hi @ssut, how do you imagine this feature in your code? Can you give an example?

**Comment by ssut** [comment]
@kachkaev i'm sorry i made a mistake while I creating a new issue. now I edited the content you can understand.

**Comment by brummelte** [comment]
Hi @ssut, thanks for the PR.

Currently I think it should go more in the direction of https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort. As that will probably be the standard way to cancel promises. This would also solve the problem that cancelled promises will be awaited for indefinitely.

Only problem with that is, that browser support is limited and it is a browser based API, so it will not be supported in node.

Might make sense to use such an implementation anyway. The caller can then decide what polyfill he wants to use. For example https://github.com/mysticatea/abort-controller.

This library then wouldn't need to add any polyfill. If a signal has been passed as an option it would then handle the abort event from the signal.

I'm not sure this library should implement a custom way to cancel the promise.

Another solution I'm considering is adding a separate function that returns a promise and the timeoutId. Something like:

```javascript
const { sleepPromise, cancel, timeoutId } = cancellableSleep();

// Then you can call either
clearTimeout(timeoutId);
// Or
cancel();
```

Of the 3 choices, my initial ranking is the following:

1. AbortController
2. cancellableSleep function
3. Custom implementation, with a `.cancel` method

But I'm not sure yet if this library should even handle it at all. I will need to think about it a little bit more, and I'm open to hear what other people think.

**Comment by brummelte** [comment]
From your example I currently cannot see why you need cancellation.

You gave the following example:
```javascript
const promise = sleep(20).then(() => true);
const timeout = sleep(50).then(() => Promise.reject("Timeout"));

Promise.race([promise.then(() => sleep(40).then(() => true)), timeout])
  .then(value => {
    console.log(1, { value });
  })
  .catch(error => {
    console.log(1, { error });
  });
```

This could easily be rewritten as:
```javascript
const promise = sleep(20).then(() => true);
const timeout = sleep(50).then(() => Promise.reject("Timeout"));

Promise.race([promise, timeout])
  .then(() => sleep(40).then(() => true))
  .then(value => {
    console.log(2, { value });
  })
  .catch(error => {
    console.log(2, { error });
  });
```

It would still reject if your event promise takes longer than timeout, but if the event promise happens before timeout it would continue, no matter how long the promise returned from the event takes.

See this CodeSandbox as an example: https://codesandbox.io/s/5ypnqyjo3l

**Comment by brummelte** [comment]
If timeout is an error condition, it might make sense to use a rejecting promise. Then you don't need an if. But you would need to wrap the whole thing in a try catch.

```javascript
await Promise.all([
  trigger(),
  Promise.race([
    dialogEventPromise().then((dialog) => dialog),
    sleep(1000).then(() => Promise.reject("Timeout")),
  ]).then((dialog) => {

  });
]);
```
But this is not really the main topic.

I understand that having the ability to cancel a timeout might make sense. But currently the standard way to cancel promises is just to ignore the ones that are not needed. I agree that it would be good to free up resources that are not needed. But I feel like that is a language level problem with promises right now. Not with this library.

I hope some other people share their opinion.

**Comment by ssut** [comment]
I mean the sleep promise is used to wait for dialogs to be appear, otherwise skip the routine. In that case, I have to write unneeded code like `.catch(() => {}) // noop`.

**Comment by brummelte** [comment]
As there are no responses yet, it seems like this is not important for many people.

I will still leave this issue open for a little while and wait for responses, but right now it seems like this will not make it into the library.

**Comment by brummelte** [comment]
Closing as there is no demand for this currently and we couldn't find a good solution.

For now unneeded promises should just be ignored.

**Comment by kachkaev** [comment]
Now that [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) is a standard web API, how about returning to this topic?

In the mean time, I use this wrapper function:
```ts
import sleep from "sleep-promise";

export class AbortError extends Error {
  constructor() {
    super();
  }
}

const abortableSleep = async (
  timeout: number,
  abortSignal: AbortSignal | undefined,
) => {
  const tick = 100;
  for (let ttl = timeout; ttl > 0; ttl -= tick) {
    if (abortSignal?.aborted) {
      throw new AbortError();
    }
    await sleep(Math.min(ttl, tick));
  }
};
```

Usage:

```ts
const abortController = new AbortController();
await Promise.race([
  doSomethingSlow(),
  abortableSleep(1000 * 60 * 60 /* 1 hr */, abortController.signal),
]);
abortController.abort();
```

If `sleep` is not abortable, the whole script does not exit for one hour because of a pending promise.
