### ISSUE TITLE
Provides a helper to delay a promise chain

### ISSUE THREAD

**Issue by dsvictor94** [brummelte/sleep-promise#3]
I imagine a method to delay a promise chain would be extremely useful.

Something to allow:

```
Promise.resolve("hello world")
    .then(sleep(5000))
    .then(x => x.toUpperCase())
    .then(x => console.log(x))
```

this can be useful to control an animation or display a notification

```
sendEmail("test@email.com")
    .then(showNotification)
    .then(sleep(200))
    .then(id => hideNotification(id))
```

what do you think?

**Comment by brummelte** [comment]
I think it's a very good idea.

But the name is not clear enough. Sleep and Delay are too similar. And I'd rather have it in the same function.

I need to think about it.

**Comment by dsvictor94** [comment]
I think the same thing as you. But is not easy turn a promise callable without add unexpected behaviors.

Your implementation, for example, start the sleep just after call then, not immediately as expected.

```
fib = n => n<=1?1:fib(n-1)+fib(n-2)

console.log(new Date())
x = sleep(5000)
fib(35) // take a long time
x.then(() => {
    console.log(new Date())
})
```

**Comment by dsvictor94** [comment]
I really liked your solution to the unexpected behaviors I exposed in the comment above but I think there are one more strange behavior as follow:

```
test('delayed chain sleep', async () => {
    const start = performance.now();

    const sleepPromise = sleep(20);

    return sleep(20)
        .then(() => 'test')
        .then(sleepPromise)  //must not sleep again becouse 'sleepPromise' already resolved
        .then(value => {
            const end = performance.now();
            expect(value).toEqual('test')
            expect(end - start).toBeGreaterThanOrEqual(19);
            expect(end - start).toBeLessThan(30);
        });
});
```
