### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by kachkaev** [brummelte/sleep-promise#6]
It'd be great if the library provided TypeScript typings! Otherwise, this warning is shown next to `import * as sleep from "sleep-promise";`:

```
Could not find a declaration file for module 'sleep-promise'.
'/path/to/project/node_modules/sleep-promise/lib/index.js' implicitly has an 'any' type.
Try `npm install @types/sleep-promise` if it exists or add a new declaration
(.d.ts) file containing `declare module 'sleep-promise';`
```

I can submit a PR if this idea gets approved.

**Comment by brummelte** [comment]
I'm not using TypeScript myself, but that would definitely be great to add. Does it maybe make more sense to implement it in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

I'm open to accepting a PR if this repository is the better place for it.

**Comment by kachkaev** [comment]
Because sleep-promise is quite small, representing it with two lines in package.json feels like a bit too much.

If I submit a PR with typings, would you be able to accept it?

**Comment by kachkaev** [comment]
BTW I’m using TypeScript for just two month, but I’m already a big fan of it! Highly recommend to check it out!

**Comment by brummelte** [comment]
As far as I understand it, typing can either be done in the file itself, in a separate index.d.ts file, or in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

I'm either for using [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) or doing it in a separate index.d.ts file. I would gladly accept a PR with an index.d.ts file.

**Comment by brummelte** [comment]
Has been added in 4.1.0.
