### ISSUE TITLE
A release without core-js

### ISSUE THREAD

**Issue by kachkaev** [brummelte/sleep-promise#74]
An unnecessary dependency on `core-js` was removed in #27 in October. However, the latest published release (9.0.0) [still includes it](https://unpkg.com/browse/sleep-promise@9.0.0/package.json). It’d be great if you could release 9.0.1 at some point, which would not include`core-js`. This may resolve certain issues related to dependency hoisting and resolution. Cheers!

**Comment by brummelte** [comment]
Good idea.

Released: [v9.1.0](https://github.com/brummelte/sleep-promise/releases/tag/v9.1.0)
